import { Event, Sponsor, User } from './types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  avatarUrl: 'https://picsum.photos/id/64/200/200',
  savedEventIds: ['e2'],
  attendedEventIds: [],
  hostedEventIds: [],
};

export const SPONSORS: Sponsor[] = [
  {
    id: 's1',
    name: 'TechFlow',
    logoUrl: 'https://picsum.photos/id/30/100/100',
    tier: 'Platinum',
    website: 'https://example.com',
    perks: ['VIP Lounge Access', 'Logo on Lanyards'],
  },
  {
    id: 's2',
    name: 'Nebula Drink',
    logoUrl: 'https://picsum.photos/id/88/100/100',
    tier: 'Gold',
    website: 'https://example.com',
    perks: ['Free Samples'],
  },
  {
    id: 's3',
    name: 'CryptoSecure',
    logoUrl: 'https://picsum.photos/id/106/100/100',
    tier: 'Silver',
    website: 'https://example.com',
    perks: [],
  }
];

export const EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'UFC 308: Las Vegas Fight Night',
    description: 'The biggest fight night of the year returns to the T-Mobile Arena. Experience the thrill live.',
    date: '2025-11-09',
    time: '20:00',
    location: 'Las Vegas, NV',
    venueName: 'T-Mobile Arena',
    format: 'In-Person',
    imageUrl: 'https://picsum.photos/id/147/800/400',
    price: 214,
    category: 'Sports',
    hostId: 'h1',
    sponsorId: 's2',
    attendees: 14500,
    capacity: 20000,
    tags: ['MMA', 'Sports', 'Live'],
    isFeatured: true,
  },
  {
    id: 'e2',
    title: 'Future of AI Summit',
    description: 'Join industry leaders to discuss the next generation of generative models.',
    date: '2025-11-15',
    time: '09:00',
    location: 'San Francisco, CA',
    format: 'Hybrid',
    imageUrl: 'https://picsum.photos/id/20/800/400',
    price: 499,
    category: 'Tech',
    hostId: 'h2',
    sponsorId: 's1',
    attendees: 1200,
    capacity: 2000,
    tags: ['AI', 'Tech', 'Networking'],
  },
  {
    id: 'e3',
    title: 'Neon Art Exhibition',
    description: 'An immersive journey through light and sound.',
    date: '2025-11-20',
    time: '18:00',
    location: 'New York, NY',
    format: 'In-Person',
    imageUrl: 'https://picsum.photos/id/56/800/400',
    price: 45,
    category: 'Art',
    hostId: 'h3',
    attendees: 300,
    capacity: 500,
    tags: ['Art', 'Culture'],
  },
  {
    id: 'e4',
    title: 'Global Dev Conference',
    description: 'Streaming live to developers worldwide.',
    date: '2025-12-01',
    time: '10:00',
    location: 'Online',
    format: 'Online',
    imageUrl: 'https://picsum.photos/id/2/800/400',
    price: 0,
    category: 'Tech',
    hostId: 'h2',
    attendees: 5000,
    capacity: 10000,
    tags: ['Code', 'Web3', 'Cloud'],
  },
  {
    id: 'e5',
    title: 'UFC 309: Championship Bout',
    description: 'The championship belt is on the line.',
    date: '2025-11-16',
    time: '19:00',
    location: 'Las Vegas, NV',
    venueName: 'MGM Grand Arena',
    format: 'In-Person',
    imageUrl: 'https://picsum.photos/id/158/800/400',
    price: 350,
    category: 'Sports',
    hostId: 'h1',
    attendees: 8000,
    capacity: 16000,
    tags: ['MMA', 'Championship'],
  },
];